version: '3.4'

services:
  catalogdb:
    image: mongo
   
  basketdb:
    image: redis:alpine  

  discountdb:
    image: postgres  

  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine  

  pgadmin:
    image: dpage/pgadmin4
    
  portainer:
    image: portainer/portainer-ce  

  catalog.api:
    image: ${DOCKER_REGISTRY-}eshopping_catalog_api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  basket.api:
    image: ${DOCKER_REGISTRY-}eshopping_basket_api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}eshopping_discount_api
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}eshopping_ordering_api
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
  
  ocelotapigw:
    image: ${DOCKER_REGISTRY-}eshopping_ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/Ocelot.ApiGateway/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:  
